🚀 Add Front End for Starklings Web
onlydustxyz/starklings pull request #237
Opened 2022-09-09 16:07 UTC by sxxnx

**There will be UI fix to be done after all back-end is done (minor CSS changes)**

Feel free to reach for any question/change/issue 😸

2022-09-13 12:05 UTC, ltoussaint requested changes
The PR is not complete, there is no `package.json` so I can not install and test the project.

Also I see the last commit removed a lot of files, especially fontawesome ones. Maybe you should change the copy of all the fontawesome files by only including what you need (I don't think we need the `scss` files for exemple) And to prevent adding to many files, maybe we could use the icons as font instead of using each svg files.


- [ ] There are a lot of import using relative path. We should configure typescript paths to be able to have imports like `import myLib from 'src/.....';`
- [ ] Add an [editor config](https://editorconfig.org/) file to force a newline at the end of each file
- [ ] Git ignore `web/front/src/output.log` file

2022-09-13 12:05 UTC, ltoussaint commented on web/front/tsconfig.json
> +    "allowJs": true,
Set this to `false` to force using typescript

2022-09-13 12:05 UTC, ltoussaint commented on web/front/tsconfig.json
> +    "esModuleInterop": true,
As it is a new project, we should set this to `false`

2022-09-13 15:04 UTC, sxxnx commented on web/front/src/store/reducers/wallet.ts
> +import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'
line 21

2022-09-13 15:05 UTC, sxxnx commented on web/front/src/store/reducers/wallet.ts
> +import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'
line 47

2022-09-13 16:14 UTC, sxxnx commented on web/front/src/components/Exercices/CodeEditor.tsx
> +        <button className='button-run-code'>Check</button>
It is not finished yet because related to back-end

2022-09-13 16:57 UTC, sxxnx commented on web/front/src/components/Exercices/FileDrop.tsx
> +    onDrop(acceptedFiles)
It is not finished as it depends on back end

2022-09-14 07:34 UTC, ltoussaint commented on web/front/src/store/reducers/wallet.ts
> +import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'
I was taking about the `store/reducers/wallet.ts`

2022-09-14 18:21 UTC, sxxnx commented
PR  would be submitted again when [this PR](https://github.com/sxxnx/starklings/pull/6) is merged so you can get a functional version

2022-09-29 12:05 UTC, closed without merging